version: "3.9"

services:
  db:
    image: mysql:8
    container_name: kinggodcastle-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kinggodcastle
      MYSQL_USER: kgc_user
      MYSQL_PASSWORD: kgc_password
      TZ: Asia/Ho_Chi_Minh
    command: --default-time-zone='+07:00'
    ports:
      - "3307:3306"
    volumes:
      - kgc_dbdata:/var/lib/mysql

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile.dev
    container_name: kinggodcastle-be
    restart: unless-stopped
    ports:
      - "9001:9000"
    volumes:
      - ./be:/var/www
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: kinggodcastle
      DB_USERNAME: kgc_user
      DB_PASSWORD: kgc_password
      TZ: Asia/Ho_Chi_Minh
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: kinggodcastle-nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./be:/var/www
      - ./be/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    container_name: kinggodcastle-fe
    restart: unless-stopped
    ports:
      - "3001:5173"
    volumes:
      - ./fe:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    command: npm run dev -- --host

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: kinggodcastle-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  kgc_dbdata:
